### ISSUE TITLE
Add latest node to travis.yml

### ISSUE THREAD

**Issue by DavidBruant** [mafintosh/protocol-buffers-schema#26]
Not sure how Travis works but it looks like only the latest iojs is tested in your repo.
From what I understand, [`node_js` environments are passed to `nvm`](https://docs.travis-ci.com/user/ci-environment/#Node.js-VM-images)
So you may want to add [`node`](https://github.com/creationix/nvm#usage) (why not remove `iojs`), because I'm not sure anyone cares any longer.

**Comment by mafintosh** [comment]
sounds good. you wanna send a pr with the changes?
