### ISSUE TITLE
[enhancement] Ensure that tag numbers have been assigned and throw an error if not

### ISSUE THREAD

**Issue by thlorenz** [mafintosh/protocol-buffers-schema#31]
Forgetting to assign a tag number to a property leads to subtle bugs. In the below example _dollars_ will round trip fine on an encode/decode, but _pesos_ will come out `null`.
It'd be nice if the parser could ensure that tags were assigned and throw an error if not to make it easier to see the problem.

```
message wallet {
  optional int32 dollars;
  optional int32 pesos;
}

message traveller {
  required wallet wallet;
}
```

**Comment by mafintosh** [comment]
fixed in latest
