### ISSUE TITLE
Reserved fields

### ISSUE THREAD

**Issue by rthewhite** [mafintosh/protocol-buffers-schema#32]
When using protobuff it's an best practice that when you remove fields from a message that you reserve the tag number to prevent issues when adding a new field again. As described in the language guide: https://developers.google.com/protocol-buffers/docs/proto

```
message Foo {
  reserved 2, 15, 9 to 11;
  reserved "foo", "bar";
}
```

Currently the parser break on this, would like to make a pull request to fix this. But i'm in doubt what the proper solution would be. Should it just skip over the reserved tags and leave them out of the JSON completely or should it parse the tags properly and mark them in the JSON somewhere as reserved?

**Comment by rthewhite** [comment]
Any ideas on this?

**Comment by mafintosh** [comment]
I havent used reserved myself but ignoring seems like a great solution for now as this seems to be mostly a hint for humans

**Comment by pgirolami** [comment]
@mafintosh Release solved the issue, thanks

**Comment by rthewhite** [comment]
Think we can close this one now the #33 is merged and released 👍
