### ISSUE TITLE
my gen error, because have parenthesis。

### ISSUE THREAD

**Issue by QuietWind** [mafintosh/protocol-buffers-schema#36]
because doc have parenthesis！and parse error。
can you help me reolve it! thanks very much.

.proto file like this:
```proto
	rpc AdminRecommendProductImport(msg) returns (msgResp) {
		option (common.auth).name = true;
	}
```

**Comment by mafintosh** [comment]
Can you add more info please? Like linking the problematic schema

**Comment by cpdeethree** [comment]
Seconding comments from above, but just looking at what you have posted here, it's not supported. See #40

**Comment by mafintosh** [comment]
Think this is fixed in latest version. If not feel free to reopen
