### ISSUE TITLE
Add imports to stringify method

### ISSUE THREAD

**Issue by kyle-schuetz** [mafintosh/protocol-buffers-schema#62]
I'd like to be able to use the library as part of a protobuf file generation project I am working on but am running into an issue where imports are not preserved when calling `parse` to transform protobuf to JSON and then calling `stringify` to stringify the JSON back into the `.proto` format.

It seems like a solution to this would be pretty simple. Happy to create a PR if desired.

**Comment by mafintosh** [comment]
Sounds good! As long as it doesn’t add any io but just parses ut I’m +1

**Comment by kyle-schuetz** [comment]
That was the idea, just parsing what is already there and adding to the string.
